Add scull module management scripts and improve loading logic

diff --git a/scull/scull_load b/scull/scull_load
--- a/scull/scull_load
+++ b/scull/scull_load
@@ -3,6 +3,7 @@
 module="scull"
 device="scull"
 mode="664"
+module_path="/lib/modules/$(uname -r)/extra/${module}.ko"
 
 # Group: since distributions do it differently, look for wheel or use staff
 if grep -q '^staff:' /etc/group; then
@@ -11,9 +12,13 @@ else
     group="wheel"
 fi
 
-# invoke insmod with all arguments we got
-# and use a pathname, as insmod doesn't look in . by default
-insmod ./$module.ko $* || exit 1
+if [ -e "${module_path}" ]; then
+    echo "Loading local built file ${module}.ko"
+    insmod "${module_path}" $* || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
+fi
 
 # retrieve major number
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
