Refactor module loading logic to use module path variable for improved clarity and maintainability

diff --git a/misc-modules/misc-modules_load b/misc-modules/misc-modules_load
--- a/misc-modules/misc-modules_load
+++ b/misc-modules/misc-modules_load
@@ -4,6 +4,8 @@ module=$1
 device=$1
 # Support read/write for owner and group, read only for everyone using 644
 mode="664"
+# 
+module_path="/lib/modules/$(uname -r)/extra/${module}.ko"
 
 if [ $# -ne 1 ]; then
 	echo "Wrong number of arguments"
@@ -21,8 +23,16 @@ else
     group="wheel"
 fi
 
+if [ -e "${module_path}" ]; then
+    echo "Loading local built file ${module}.ko"
+    insmod "${module_path}" $* || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
+fi
+
 echo "Load our module, exit on failure"
-insmod ./$module.ko $* || exit 1
+insmod "${module_path}" $* || exit 1
 echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 if [ ! -z ${major} ]; then
